# Generated by Django 5.0.6 on 2024-05-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactMaxapp', '0004_subscriptionplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='numberofcontacts',
            new_name='maximumcontacts',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
