# Generated by Django 5.0.6 on 2024-05-30 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactMaxapp', '0005_rename_numberofcontacts_subscriptionplan_maximumcontacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.ManyToManyField(to='contactMaxapp.category'),
        ),
        migrations.AddField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contactMaxapp.customuser'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptionplan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactMaxapp.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contactMaxapp.customuser')),
            ],
        ),
    ]
